python main.py --dataset Mnist-alpha0.1-ratio0.5 \
               --algorithm FedSP \
               --batch_size 32 \
               --num_glob_iters 500 \
               --local_epochs 20 \
               --num_users 10 \
               --lamda 1 \
               --learning_rate 0.01 \
               --model cnn \
               --personal_learning_rate 0.01 \
               --times 1 \
